apiVersion: v1
kind: Pod
metadata:
  name: web-api
  labels:
    type: unicorn
    vendor: yaa
spec:
  containers:
  - name: web-api
    image: vsuzdaltsev/web_api:0.0.1
    ports:
      - containerPort: 4567
    env:
    - name: APP_DIR
      value: '/opt/app'
    - name: RUBY_VER
      value: '2.5.0'
    - name: UNICORN_PORT
      value: '4567'
    - name: UNICORN_HOST
      value: '127.0.0.1'
    - name: UNICORN_TIMEOUT
      value: '5'
    - name: UNICORN_WORKERS
      value: '2'
    - name: UNICORN_CONTAINER_NAME
      value: 'unicorn'
    command: ["/usr/local/bundle/bin/unicorn"]
    args: ["-c", "/opt/app/unicorn.conf"]
