language: minimal

sudo: required
services:
  - docker

branches:
  only:
  - master

before_install:
  - rake docker_compose:build
  - rake docker_compose:run
  - rake test:rspec
  - rake docker_compose:stop

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vsuzdaltsev/web_api:latest
