version: '3'
services:
  unicorn:
    environment:
      APP_DIR: ${APP_DIR}
      UNICORN_PORT: ${UNICORN_PORT}
      UNICORN_HOST: ${UNICORN_HOST}
      UNICORN_TIMEOUT: ${UNICORN_TIMEOUT}
      UNICORN_WORKERS: ${UNICORN_WORKERS}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUBY_VER: ${RUBY_VER}
        APP_DIR: ${APP_DIR}
    command: unicorn -c ${APP_DIR}/unicorn.conf
    ports:
      - ${UNICORN_PORT}:${UNICORN_PORT}
    container_name: ${UNICORN_CONTAINER_NAME}
    image: ${UNICORN_CONTAINER_NAME}_img
